# Generated by Django 5.1.3 on 2025-01-08 03:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0009_booking_payment_status_booking_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='price',
            new_name='rent',
        ),
    ]
