# Generated by Django 5.1.5 on 2025-02-05 02:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0017_alter_booking_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='profile',
        ),
    ]
