# Generated by Django 5.1.4 on 2025-02-06 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0019_remove_booking_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(blank=True, default='images/profile_pics/default.png', null=True, upload_to='images/profile_pics/'),
        ),
    ]
