# Generated by Django 5.1.4 on 2025-02-09 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0022_alter_profile_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='payment_method',
            field=models.CharField(choices=[('UPI', 'Upi'), ('Card', 'Card'), ('Cash on Delivery', 'Cashondelivery')], default='Cash on Delivery', max_length=50),
        ),
    ]
