# Generated by Django 3.2.21 on 2024-12-25 06:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='car_pics')),
                ('name', models.CharField(max_length=50)),
                ('capacity', models.IntegerField()),
                ('mileage', models.IntegerField()),
                ('engine', models.CharField(max_length=20)),
                ('gear', models.CharField(max_length=20)),
                ('available', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cus_name', models.CharField(max_length=50)),
                ('cus_ph', models.CharField(max_length=12)),
                ('cus_email', models.CharField(max_length=30)),
                ('pickup_date', models.DateField()),
                ('return_date', models.DateField()),
                ('booked_on', models.DateField(auto_now=True)),
                ('notes', models.TextField()),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.car_info')),
            ],
        ),
    ]
