# Generated by Django 5.1.4 on 2024-12-25 08:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mainapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="car_info",
            name="slug",
            field=models.SlugField(blank=True, max_length=100, unique=True),
        ),
        migrations.AddField(
            model_name="car_info",
            name="year",
            field=models.IntegerField(default=2024),
        ),
    ]
