# Generated by Django 5.1.4 on 2024-12-29 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_alter_booking_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='booking',
            name='total_rent',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
