# Generated by Django 5.1.3 on 2025-01-08 03:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0010_rename_price_booking_rent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car_info',
            old_name='price',
            new_name='rent',
        ),
    ]
