# Generated by Django 5.1.5 on 2025-02-05 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0013_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(blank=True, default='media/images/profile_pics/default.png', null=True, upload_to='media/images/profile_pics/'),
        ),
    ]
