# Generated by Django 5.1.5 on 2025-02-05 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0014_alter_profile_profile_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car_info',
            name='gear',
        ),
        migrations.AddField(
            model_name='car_info',
            name='transmission',
            field=models.CharField(choices=[('Manual', 'Manual'), ('Automatic', 'Automatic')], default='Manual', max_length=15),
        ),
        migrations.AlterField(
            model_name='booking',
            name='payment_status',
            field=models.CharField(choices=[('Paid', 'Paid'), ('Pending', 'Pending')], default='Pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('Booked', 'Booked'), ('Rented', 'Rented'), ('Completed', 'Completed')], default='Booked', max_length=10),
        ),
        migrations.AlterField(
            model_name='car_info',
            name='engine',
            field=models.CharField(choices=[('Hybrid', 'Hybrid'), ('Petrol', 'Petrol'), ('Diesel', 'Diesel')], default='Petrol', max_length=10),
        ),
    ]
