# Generated by Django 5.1.5 on 2025-02-05 02:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0015_remove_car_info_gear_car_info_transmission_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.profile'),
        ),
        migrations.AddField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='cus_email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='booking',
            name='cus_ph',
            field=models.CharField(max_length=15),
        ),
    ]
