# Generated by Django 5.1.4 on 2025-02-06 02:13

import mainapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0020_alter_profile_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(blank=True, default='images/profile_pics/default.png', null=True, upload_to=mainapp.models.profile_image_path),
        ),
    ]
