# Generated by Django 5.1.4 on 2025-02-09 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0024_booking_notes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='notes',
            new_name='address',
        ),
    ]
